### PR TITLE
Want to publish it to testnet

### PR DESCRIPTION
**Pull request by SergeyAnkarenko**
This smart contract was developed for stratis hackathon
 
Could you please publish this smart contract to testnet. 

This is not a final version, because I didn't add tests for example, but its very important for me to publish it to testnet and make sure that everything works as expected, so I don't have any surprizes right before deadline. 

I have developed startisjs library so transactions can be created/signed on client side, so anyone can visit my website, login with private key and play with the smart contract, thats why I want it to be published on testnet, not on private network

Description, hash, bytecode... All this data is described in readme in a root folder of the project
https://github.com/SergeyAnkarenko/CirrusSmartContracts/tree/master/Testnet/WheelGame

NOTE, when publishing smart contract supply two parameters in constructor
1: ULong 10000000
2: Byte: 7

Thanks!

### CODE REVIEW

**Comment by codingupastorm** [comment]
hey hey @SergeyAnkarenko I've sent the word internally to whitelist this! It should happen on Monday London time. Feel free to ping me whenever for an update in case in you don't hear back by then.

**Comment by SergeyAnkarenko** [comment]
I have added new tests and changed smart contract code a little bit, so smart contract hash and byte code were changed accordingly. This is a final version. If you can whitelist it on testnet that would be great!!

**Comment by StratisIain** [comment]
Whitelisted

**Comment by StratisIain** [comment]
{     "isPending": false,     "isExecuted": false,     "id": 23,     "pollVotedInFavorBlockData": "b660e92d69de4d50b5f52ecec6a64ec2a6284af94ea80b1414f8e71073ca8b06f0401000",     "pollStartBlockData": "3761845e271c0c04d630a62bf496187f314e729ea18e985c6a7b165f85ad8dc2dd401000",     "pollExecutedBlockData": null,     "pubKeysHexVotedInFavor": [       "022553fb641898be98e6e331d644c1689455536e58ad643d84844e981708da38e9",       "02fc828e06041ae803ab5378b5ec4e0def3d4e331977a69e1b6ef694d67f5c9c13",       "02fd4f3197c40d41f9f5478d55844f522744258ca4093b5119571de1a5df1bc653",       "030ac8e3e119257aff4512ea44450632a6a9b54104f936732d31c28a63a2104064",       "024142689f38fdb5e8faf3bc7bc5065ecaad6be93a34055ffce0554f9268639c98",       "03382ceb0a59b9b922aca6be9959ae51dabda159e79465393a308ee267ecebcaa5",       "027d31e9dc3ee5a42b1273ae8184e716fc616fed6d7b62323fa0a33901d188cfeb",       "03d8e88797b56894a0d8ce6421defd4572fc8d19e18321d07ea22a6adec59f7fd1"     ],     "votingDataString": "Action:'WhitelistHash',Hash:'23f881e111c9453b36c8265ad53339df56837eea256814b2077b6fb7c6b92c95'"   }
--

**Pull request merged**
